name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: 'https://npm.pkg.github.com'
    - name: Publish to gh registry
      run: |
        yarn policies set-version 1.19.1
        yarn
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install github-release-notes and generate changelog
      run: |
        npx github-release-notes changelog --generate --override --token=${{ secrets.GITHUB_TOKEN }} --changelog-filename=TEMP_CHANGELOG.md
      env:
        CI: true
    - name: Create and publish realese
      uses: ncipollo/release-action@v1
      with:
        bodyFile: 'TEMP_CHANGELOG.md'
        token: ${{ secrets.GITHUB_TOKEN }}

